---
title: "Pitchers"
author: "Jason Scheer"
date: "2024-04-28"
output: pdf_document
---


```{r}
library(readr)
library(tidyverse)
library(dplyr)
hit = read_csv("hit.csv")
non_hit1 = read_csv("non_hit1.csv")
non_hit2 = read_csv("non_hit2.csv")
non_hit = rbind(non_hit1, non_hit2)


# This is what I used to get those csv files


#library(tidyverse)
#library(Lahman)
#library(readr)
#
#
#sc = read_csv("~/Downloads/statcast.csv")
#
#sc2 = sc |> 
#  select(c("pitcher_name", "pitch_type", "game_year", "zone", "p_throws", "type", "stand", #"plate_x", "plate_z", "hc_x", "hc_y", "sz_top", "sz_bot", "hit_distance_sc", "launch_speed", #"launch_angle"))
#
#
#
#non_hit1 = sc2 |> 
#  filter(type != "X") |> 
#  select(c("pitcher_name", "pitch_type", "game_year", "zone", "type", "stand", "plate_x", #"plate_z", "sz_top", "sz_bot")) |> 
#  filter(game_year < 2020)
#
#non_hit2 = sc2 |> 
#  filter(type != "X") |> 
#  select(c("pitcher_name", "pitch_type", "game_year", "zone", "type", "stand", "plate_x", #"plate_z", "sz_top", "sz_bot")) |> 
#  filter(game_year >= 2020)
#
#hit = sc2 |> 
#  filter(type == "X")


# I had to divide the non hits into two because of the file size
```



```{r}
# I'm making a pitch count variable so it only shows pitchers who threw a lot in a season
pitch_count = non_hit |> 
  group_by(pitcher_name, game_year) |> 
  summarise(total_pitches = n(), .groups = "keep") |> 
  filter(total_pitches >= 1000) # Arbitrary number to filter out players who didn't pitch much in a season 

# create a variable to use for Shiny app when sorting by pitchers
unique_pitchers = unique(pitch_count$pitcher_name) 
unique_pitchers = unique_pitchers[unique_pitchers != "Reynald"] # For some reason this was in both and messed with my data
non_hit = non_hit |> 
  filter(pitcher_name != "Reynald")

# Removes accents so R Shiny can display everyone
remove_accents = function(string) {
  iconv(string, "ASCII//TRANSLIT")
}
# Ran unique pitchers through the function and sort alphabetically
unique_pitchers = lapply(unique_pitchers, remove_accents)
unique_pitchers = unlist(unique_pitchers)
unique_pitchers = sort(unique_pitchers)



# Did the same thing for hit data frame


pitch_count2 = hit |> 
  group_by(pitcher_name, game_year) |> 
  summarise(total_hits = n(), .groups = "keep") |> 
  filter(total_hits >= 100) # Arbitrary number to filter out players who didn't pitch much in a season 

unique_pitchers2 = unique(pitch_count2$pitcher_name) 
unique_pitchers2 = unique_pitchers2[unique_pitchers2 != "Reynald"]
hit = hit |> 
  filter(pitcher_name != "Reynald")


unique_pitchers2 = lapply(unique_pitchers2, remove_accents)
unique_pitchers2 = unlist(unique_pitchers2)
```


```{r}
# Created a function to create a rough MLB field for balls in play

spray_chart = function(...) {
  ggplot(...) + 
    geom_curve(x = 33, xend = 223, y = -100, yend = -100, curvature = -0.65, color = "black") + 
    geom_segment(x = 128, xend = 33, y = -208, yend = -100, color = "black") + 
    geom_segment(x = 128, xend = 223, y = -208, yend = -100, color = "black") + 
    geom_curve(x = 83, xend = 173, y = -155, yend = -156, curvature = -0.65, linetype = "dotted", color = "black") + 
    coord_fixed() + 
    scale_x_continuous(NULL, limits = c(25, 225)) + 
    scale_y_continuous(NULL, limits = c(-225, -25))
}
```





```{r}
# Download library
library(shiny)

# UI
ui = navbarPage(
  title = "Pitchers Location",
  tabPanel(
    title = "Pitcher's non-hits Strike Zone",
    titlePanel(title = "MLB Statcast data: 2017-2022"),
    sidebarLayout(
      sidebarPanel(
        selectInput(
          inputId = "pitcher",
          label = "Pitcher: ",
          choices = unique_pitchers,
          selected = "Justin Steele"
        ),
        selectInput(
          inputId = "stand",
          label = "Against Lefty or Righty?",
          choices = c("Lefty" = "L", "Righty" = "R", "Both" = "Both"),
          selected = "Both"
        ),
        selectInput(
          inputId = "pitch_type",
          label = "Pitch Type",
          choices = c(
            "Change-Up" = "CH", "Curveball" = "CU", "Cutter" = "FC",
            "Four-seam Fastball" = "FF", "Forkball" = "FO", "Splitter" = "FS",
            "Two-seam Fastball" = "FT", "Knuckle Curve" = "KC", "Knuckleball" = "KN",
            "Screwball" = "SC", "Sinker" = "SI", "Slider" = "SL"
          ),
          selected = "FF"
        ),
        selectInput(
          inputId = "year",
          label = "Year",
          choices = c(
            "2017" = 2017, "2018" = 2018, "2019" = 2019,
            "2020" = 2020, "2021" = 2021, "2022" = 2022, "All" = "All"
          ),
          selected = "All"
        ),
        selectInput(
          inputId = "ball",
          label = "Strikes or Balls?",
          choices = c("Both" = "Both", "Strikes" = "S", "Balls" = "B"),
          selected = "Both"
        )
      ),
      mainPanel(plotOutput("plot1"))
    )
  ),
  tabPanel(
    title = "Pitcher's Hitted Balls Strike Zone",
    titlePanel(title = "MLB Statcast data: 2017-2022"),
    sidebarLayout(
      sidebarPanel(
        selectInput(
          inputId = "pitcher2",
          label = "Pitcher: ",
          choices = unique_pitchers2,
          selected = "Justin Steele"
        ),
        selectInput(
          inputId = "stand2",
          label = "Against Lefty or Righty?",
          choices = c("Lefty" = "L", "Righty" = "R", "Both" = "Both"),
          selected = "Both"
        ),
        selectInput(
          inputId = "pitch_type2",
          label = "Pitch Type",
          choices = c(
            "Change-Up" = "CH", "Curveball" = "CU", "Cutter" = "FC",
            "Four-seam Fastball" = "FF", "Forkball" = "FO", "Splitter" = "FS",
            "Two-seam Fastball" = "FT", "Knuckle Curve" = "KC", "Knuckleball" = "KN",
            "Screwball" = "SC", "Sinker" = "SI", "Slider" = "SL"
          ),
          selected = "FF"
        ),
        selectInput(
          inputId = "year2",
          label = "Year",
          choices = c(
            "2017" = 2017, "2018" = 2018, "2019" = 2019,
            "2020" = 2020, "2021" = 2021, "2022" = 2022, "All" = "All"
          ),
          selected = "All"
        )
      ),
      mainPanel(plotOutput("plot2"))
    )
  ),
  tabPanel(
    title = "Pitcher's Hitted Balls",
    titlePanel(title = "MLB Statcast data: 2017-2022"),
    sidebarLayout(
      sidebarPanel(
        selectInput(
          inputId = "pitcher3",
          label = "Pitcher: ",
          choices = unique_pitchers2,
          selected = "Justin Steele"
        ),
        selectInput(
          inputId = "stand3",
          label = "Against Lefty or Righty?",
          choices = c("Lefty" = "L", "Righty" = "R", "Both" = "Both"),
          selected = "Both"
        ),
        selectInput(
          inputId = "pitch_type3",
          label = "Pitch Type",
          choices = c(
            "Change-Up" = "CH", "Curveball" = "CU", "Cutter" = "FC",
            "Four-seam Fastball" = "FF", "Forkball" = "FO", "Splitter" = "FS",
            "Two-seam Fastball" = "FT", "Knuckle Curve" = "KC", "Knuckleball" = "KN",
            "Screwball" = "SC", "Sinker" = "SI", "Slider" = "SL"
          ),
          selected = "FF"
        ),
        selectInput(
          inputId = "year3",
          label = "Year",
          choices = c(
            "2017" = 2017, "2018" = 2018, "2019" = 2019,
            "2020" = 2020, "2021" = 2021, "2022" = 2022, "All" = "All"
          ),
          selected = "All"
        ),
        selectInput(
          inputId = "event3",
          label = "Event",
          choices = c(
            "Double" = "double", "Field Error" = "field_error", "Out" = "field_out",
            "Fielder's Choice" = "fielders_choice", "Force Out" = "force_out", "GIDP" = "grounded_into_double_play", "Home Run" = "home_run", "Sacrifice Fly" = "sac_fly", "Single" = "single", "Triple" = "triple", "All" = "All"
          ),
          selected = "All"
        )
      ),
      mainPanel(plotOutput("plot3"))
    )
  ),
  tabPanel(title = "About", includeMarkdown("So this R Shiny App looks at how pitchers, from 2017-2022, perform with each of their pitch types. The first plot shows where each pitch type is thrown in a general strike zone. It can also be filtered by lefty or righty batters and what year you want to look at. I also included an input to see the called balls and strikes for each pitch type. The second plot shows where he pitch that was hit was located, for the ones that have that data (some are missing data points). This also can be filtered by pitches, year and which side of batters. The third plot shows where in the field each ball in play was hit to while also showing the event outcome of the play. You once again can filter by year, pitch type, lefties or righties and you can look at specific events like HRs or Doubles. This won't be every pitcher because my computer could only handle so many pitchers in the filter, so I put a minimum number of pitches thrown or hits allowed to qualify."))
)

# Server
server = function(input, output, session) {
  
  output$plot1 = renderPlot({
    filtered_data = non_hit |> 
      filter(
        pitcher_name == input$pitcher,
        pitch_type == input$pitch_type
      )
    
    if (input$year != "All") {
      filtered_data = filtered_data |> 
        filter(game_year == input$year)
    }
    
    if (input$stand != "Both") {
      filtered_data = filtered_data |> 
        filter(stand == input$stand)
    }
    
    if (input$ball != "Both") {
      filtered_data = filtered_data |> 
        filter(type == input$ball)
    }
    
    p = ggplot(filtered_data, aes(x = plate_x, y = plate_z, color = factor(type, levels = c("S", "B")))) +
      geom_point() + 
      geom_rect(
        xmin = -0.83, xmax = 0.83,
        ymin = 1.17, ymax = 3.92,
        fill = NA, color = "black", linetype = "dashed"
      ) +  
      labs(x = "Horizontal Location", y = "Vertical Location", color = "Pitch Call") +  
      ggtitle("Pitcher Location") +  
      theme_minimal() +  
      scale_color_manual(values = c("red", "blue"), labels = c("Strikes", "Balls")) +  
      coord_cartesian(xlim = c(-2, 2), ylim = c(0, 5)) +
      guides(color = guide_legend(title = "Pitch Call"))
    
    p
  })
  
  
  output$plot2 = renderPlot({
    filtered_data2 = hit |> 
      filter(
        pitcher_name == input$pitcher2,
        pitch_type == input$pitch_type2
      )
    
    if (input$year2 != "All") {
      filtered_data2 = filtered_data2 |> 
        filter(game_year == input$year2)
    }
    
    if (input$stand2 != "Both") {
      filtered_data2 = filtered_data2 |> 
        filter(stand == input$stand2)
    }
    
    p2 = ggplot(filtered_data2, aes(x = plate_x, y = plate_z, color = pitch_type)) +
      geom_point() + 
      geom_rect(
        xmin = -0.83, xmax = 0.83,
        ymin = 1.17, ymax = 3.92,
        fill = NA, color = "black", linetype = "dashed"
      ) +  
      labs(x = "Horizontal Location", y = "Vertical Location", color = "Pitch Type") +  
      ggtitle("Pitcher Location") +  
      theme_minimal() +  
      coord_cartesian(xlim = c(-2, 2), ylim = c(0, 5))
    
    p2
  })
  
  output$plot3 = renderPlot({
    filtered_data3 = hit |> 
      filter(
        pitcher_name == input$pitcher3,
        pitch_type == input$pitch_type3
      )
    
    if (input$year3 != "All") {
      filtered_data3 = filtered_data3 |> 
        filter(game_year == input$year3)
    }
    
    if (input$stand3 != "Both") {
      filtered_data3 = filtered_data3 |> 
        filter(stand == input$stand3)
    }
    
    if (input$event3 != "All") {
      filtered_data3 = filtered_data3 |> 
        filter(events == input$event3)
    }
    
    p3 = spray_chart(filtered_data3, aes(x=hc_x, y=-hc_y, color=events)) +
      geom_point() + 
      theme_minimal()
    
    p3
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```


